---
title: "Exercise for 02 - Importing and Exploring Data"
output: html_document
---

## Importing NHANES data from a CSV file

Take a look at the *Files* pane on the bottom right. Note that there is a file named *biochem_long.csv*. The objective of this exercise is to *import* that CSV file into R as a data frame, and then take a first look at its contents using the *Data Viewer*.

Recall that to import CSV files, we use the *read_csv()* function, which is part of the *tidyverse* package. The *read_csv()* function takes a *filename* as an argument and returns a *data frame*. To capture the data frame in a named object, we use the *assignment operator* ( <- ).

In the following code chunk, we first load the *tidyverse* package and then use the *read_csv()* function to load the *biochem_long.csv* file and capture it in an object named *biochem*. 

Run the following code chunk.


```{r, message = FALSE}
library(tidyverse)
biochem <- read_csv("biochem_long.csv") 
```

Hint: click on the green triangle in the upper right corner of the code chunk!


## Inspecting a data frame

One thing that Excel does well is to provide an interactive visual representation of the data. This allows you to inspect it by sorting and filtering. RStudio actually does this well, too, with one difference - it won't let you *change* any of the data while you inspect it.

Look on the right at the *Environment* pane (you might have to click on the "Environment" tab) and find the entry *biochem*. This is the data frame you just created inside of R's memory. (If you don't see biochem, try running the code chunk above again).

Click on the *biochem* entry with your mouse. This will trigger the *Data Viewer* to appear in the upper-left quadrant of your screen. The *Data Viewer* allows you to visually explore your dataframe, much like a spreadsheet. You can learn a lot about a data set by visually inspecting it in this way.

Without writing any code, just by working with the Data Viewer, try to answer the following questions:

  1. How many rows are in the data frame? How many columns?
  
  2. Go ahead and try to edit one of the values in this viewer. You will find that you can't. It would have been easy for the RStudio programmers to allow editing of specific values, but they decided not to add that feature. Why do you think this was designed that way?

  3. Each row in *biochem* represents a single test. What is the age of the youngest patient in the data set? What is their gender? What is the age of the oldest patient in the data set? What is their gender?

  4. How many albumin tests were performed? How many albumin tests were performed on female patients? (Hint: look at the Filter button)
  
