---
title: "Chemistry Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)


biochem <- read_csv("biochem_long.csv")
lyte_data <- biochem |> 
  filter(test %in% c('sodium', 'potassium', 'chloride', 'bicarbonate'))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distributions for Electrolyte Results

```{r, fig.width=10}
ggplot(data = lyte_data) +
  geom_histogram(mapping = aes(x = value), bins = 50) +
  facet_grid(cols = vars(test), rows = vars(gender), scales = "free")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Age Distribution of Patients

```{r}
patient_list <- biochem |> 
  group_by(mrn, last_name, gender, age, pregnancy_status_at_exam) |> 
  summarize(num_tests = n())
ggplot(patient_list, aes(x = age)) + 
  geom_histogram(binwidth = 1)
```

### Cholesterol-Glucose Comparison

```{r}
chol_gluc_comparison <- biochem |> 
  filter(test %in% c('cholesterol', 'glucose')) |> 
  select(mrn, gender, age, pregnancy_status_at_exam, test, value) |> 
  pivot_wider(names_from = test, values_from = value)
ggplot(data = chol_gluc_comparison) +
  geom_point(aes(x = cholesterol, y = glucose))
```

